#!/bin/bash

VERSION=$(curl --silent "https://api.github.com/repos/christgau/wsdd/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')

docker push "$IMAGE_NAME"
docker push "$DOCKER_REPO:$VERSION"
