on:
  push:
  schedule:
    - cron: "0 23 * * *"

jobs:
  get-version:
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.version-step.outputs.VERSION }}
    steps:
      - name: Get latest version
        id: version-step
        shell: bash
        run: >
          echo VERSION=$(curl --silent 'https://api.github.com/repos/christgau/wsdd/releases/latest' | grep -Po '"tag_name": "\K.*?(?=")') >> $GITHUB_OUTPUT
  docker:
    needs: get-version
    uses: guillaumedsde/qbittorrent-distroless/.github/workflows/docker.yml@master
    with:
      software-version: ${{ needs.get-version.outputs.version }}
      platforms: |
        linux/amd64
        linux/arm64
    secrets: inherit
